language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10'
- '12'
cache:
    npm: false
env:
    global:
    # lambda_deploy_aws_key
    - secure: nQdKCIlXUaFdWfHcZWj7nOU3Itn1UbIbznmOQ5VpDSqC6VxO1D0V5EceFxfyz2Icqmc7VfUFW1PXtts17vzijAfmpesNJP7ZcCmiI4MIvBstngkz1h2HvKLFMoiNWmOH3aGDbyLJhouUDzPuizBmuNP3VxzcoC4dfY23+GW+oPl3XK094gI++6x00QQjcMxGhBi5gO7G4uxT2cKguDmENOqpKcNv58mq6G7muQSLI7OnMbTiikpuZPAyxpWURa8iYA+N6UDjM/SeBNUVsmM9Z9/zA8l9H8fTNxyTIPn3ksSESnC3n9BNrE6cWTon4HbbjcEfM4js172Or7m0Z7rWlrZtxb8GFW5UqbwyE9Hb4/8JrDxrD9VitG1XsQP+26uJs/noytly3/HTPaldXGkzBoXroo7/PtIsubJGmor62l68I+c/f1yF9sxpI3zexlExiAZoAwK1mwf5bruJGNa6GZVQyMSB5SNVyl2cw8VYom15hWGL0VKsoBIXoJ15A0NpnVp7ne11Lf/9has6mG0Jzqur8wYTeH8rvjyVD3WwLzz9BKoq7zmpHnFYCW5mdH4UFPZ6p3AVkdMr7umBw/rMSf7iuButlBhyydSAcXGNcnBtfNBBnwM0Wh+ehdQNbDkAuKJdfLoPcz2T3V2iIbxKX1VEeCxbjDNxZrOqIk5Zut4=
    # lambda_deploy_aws_secret
    - secure: MhIUU3fpEOlmJuyvyhLYl9MDZq/wdHMvJwAqIjy9C+bndocvwZT1C+isu24AX4YO/5BQgA8u3itKP/6qZXy3zlTZZcM/FaoBoptXc7LTdlANF6li6sqkdpEQP0g3ZoWH6QXE0ux6HvQINP0WGMv4/QFyCGrqwzoiklYiNwGIfcBR7VA0ix++DNudJL9SKvPIVXndswpn/rx3F8BUStGe+R4x0lqBBK6qKixfKXHfjo71uA61kQjlwwM2s5N2+BQU0KofG7M+RzLARkJ35lD5djuwMP+deYXSWalb0jX4P/EAud3z+7evtjS8/vVs1F3u/MgcqJKW8SheERmOFzv62757m9TZiQ01JexkLQUcWkwErhu0eJr3dpSKwUjQTB1BbBquMI2Yl7Duue4pkEQbNUayaS1WbUCGXOm3rI8zlcr3Uz4p9dCg3bgtCCvAd8o/qLIfJ706gmylib4b3iu4IJTiJ0WarwtuBiJHt2DbWv5Dq7wmrhhe574MOFVb/Zl3ngnUmlGyfX+9b79xiSReDiQftZuJVpUQ5tqTDGk1RWePtvQNKfHsfqbBPOQ2eznb9lTn13+3DUliZ1AKRZoEGFuti+jLyyYmHh+7KhbTda15fgy1lcygq5dfNNN7U6OofsvTAk6I7UAWfy2N+5ulodJ1jSbTwql1WHBLUrS+2HA=
